name: VGC Watch

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'   # every 10 minutes (UTC)

permissions:
  contents: read

jobs:
  watch:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}      # webhook for embeds
      DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}  # bot token for channel rename
      VOICE_CHANNEL_ID: '1396105985537343538'               # <- your voice channel ID
      SUPPORTED_VGC: '1.17.12.4'
      ALWAYS_SEND: '1'
      MENTION: '<@everyone>'        # ping on mismatch
      MENTION_SAFE: '<@everyone>'   # ping when compatibility restored
      # Optional testing/tuning:
      # DEBUG: '1'
      # ALERT_ON_MISMATCH: '1'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load previous state (rolling cache)
        uses: actions/cache@v4
        with:
          path: .state
          key: state-${{ runner.os }}-${{ github.run_number }}
          restore-keys: |
            state-${{ runner.os }}-

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run VGC watcher
        run: node check.cjs
