name: VGC Watch

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'   # every 10 minutes

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run VGC watcher
        run: node check.cjs
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          SUPPORTED_VGC: '1.17.12.4'
          # MENTION: '<@&ROLE_ID>'      # optional
          # ALERT_ON_MISMATCH: '1'      # optional
           ALWAYS_SEND: '1'            # optional (testing)
          # DEBUG: '1'                  # optional (testing)
