name: Monitor LoL (per region) & VGC – TEST

on:
  schedule:
    - cron: "*/10 * * * *"     # her 10 dakikada bir
  workflow_dispatch: {}         # elle tetikleme

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # .state klasörünü sakla/geri yükle (rolling cache)
      - name: Load previous state (rolling cache)
        uses: actions/cache@v4
        with:
          path: .state
          key: state-${{ runner.os }}-${{ github.run_number }}
          restore-keys: |
            state-${{ runner.os }}-

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      # (Teşhis) Webhook gizlisi var mı? (uzunluğu yazdır – içerik maskelenir)
      - name: Check webhook secret presence
        run: |
          if [ -z "${DISCORD_WEBHOOK}" ]; then
            echo "❌ DISCORD_WEBHOOK is EMPTY"; exit 1
          fi
          echo "✅ DISCORD_WEBHOOK length: ${#DISCORD_WEBHOOK}"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      # (Teşhis) Minik bir duman testi: webhook'a kısa bir mesaj gönder
      - name: Smoke test webhook
        run: |
          code=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Content-Type: application/json" \
            -d '{"content":"🧪 Webhook smoke test from GitHub Actions"}' \
            "${DISCORD_WEBHOOK}")
          echo "Webhook HTTP: $code"
          if [ "$code" -ge 400 ]; then echo "❌ Webhook failed"; exit 1; fi
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      # Asıl izleyici
      - name: Run watcher
        run: node check.cjs
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          LOL_REGIONS: "euw,na,kr,br,lan,tr"
          ALWAYS_SEND: "1"   # her çalıştırmada mesaj atsın (testten sonra kaldır)
          DEBUG: "1"         # denenen URL/HTTP kodlarını log ve mesaja yaz (testten sonra kaldır)
