name: Monitor LoL (per region) & VGC – DEBUG
on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch: {}
permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Load previous state
        uses: actions/cache@v4
        with:
          path: .state
          key: state-cache

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run watcher (DEBUG)
        run: node check.cjs
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          LOL_REGIONS: "euw,na,kr,br,lan,tr"
          ALWAYS_SEND: "1"   # test: her çalıştırmada mesaj at
          DEBUG: "1"         # test: denenen URL ve HTTP kodları mesajda görünsün
