name: VGC Watch

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

permissions:
  contents: read

jobs:
  watch:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      SUPPORTED_VGC: '1.17.12.4'
      ALWAYS_SEND: '1'   # ← TEST MODU: her çalıştırmada mesaj göndersin
      DEBUG: '1'         # ← (opsiyonel) debug alanını gösterir
      # MENTION: '<@&ROLE_ID>'
      # MENTION_SAFE: '<@&ROLE_ID>'
      # ALERT_ON_MISMATCH: '1'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run VGC watcher
        run: node check.cjs
